# Generated by Django 4.2.2 on 2023-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
