# Generated by Django 4.2.2 on 2023-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(default='CR', max_length=100),
        ),
    ]
