# Generated by Django 4.2.2 on 2023-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='bio',
            field=models.TextField(max_length=2000),
        ),
    ]
