# Generated by Django 4.2.2 on 2023-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_place_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='typefull',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
