# Generated by Django 4.2.2 on 2023-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_place_typefull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='typefull',
            field=models.CharField(max_length=100),
        ),
    ]
