INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('CR', 'For Cultural Riches', 'Alexandria, Virginia', 'https://www.travelandleisure.com/thmb/MfbcFrbzf8_tHsBtuYaKl4jHJ7s=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-king-street-alexandria-virginia-WTG2023-904fefe1290f4a3a91b53a7b40f61ae9.jpg', 'With postcard-perfect cobblestone streets and quick access to the wineries of northern Virginia, Alexandria is an easy city to love. But these days, the reason to go is to see how effectively the city is confronting its own history, as destinations across the American South grapple with the legacy of the Confederacy. Alexandria, which was founded as a tobacco port in 1749, was for decades of the 19th century the site of the country’s largest domestic slave trade. Today, the Freedom House Museum has three new exhibitions honoring the people who were forcibly brought here. Meanwhile, the African American Heritage Trail, which opened in 2020, follows the Potomac River and encompasses nearly 200 years of history at 11 stops, such as the Torpedo Factory, where many Black men and women worked during World War II. An extension of the route will debut in February 2023 with 20 new stops, including Waterfront Park, the port from which enslaved people were trafficked to places like New Orleans. At Jones Point Park, visitors can learn about Benjamin Banneker, an inventor, mathematician, and free African American from Maryland who was instrumental in the 1791 surveying team that determined the border of the new U.S. capital of Washington, D.C. (For an even deeper look at the city’s Black experience, book with Manumission Tours, which is run by a fourth-generation Alexandrian.) The city’s most elegant stay is Morrison House Old Town Alexandria, Autograph Collection, which was recently voted one of the best city hotels in the continental U.S. in T+L’s 2022 World’s Best Awards. A new Hotel AKA is slated to open in Old Town in winter 2023. — Liz Cantrell');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
    ('CR', 'For Cultural Riches', 'Cairo and the Nile', 'https://www.travelandleisure.com/thmb/JbknKo9QBBP20qVSkTSvqRBJ_fE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-cairo-egypt-nile-river-cruise-WTG2023-88ecdf3043724d9e914739aa2140940c.jpg', 'It’s almost here: After more than a decade of construction — to say nothing of the hype — the Grand Egyptian Museum may finally open, just a stone’s throw from the Great Pyramids of Giza, this spring. What to expect? More than 1 million square feet of exhibition space, treasures including a 40-foot-high statue of Ramses II, outdoor gardens, and an expansive plaza from which visitors can take in the desert surroundings. Meanwhile, a number of new and luxurious ships have started sailing the Nile: Among the best choices are the Viking Osiris, an all-veranda vessel carrying 82 passengers, and the opulent Sphinx from Uniworld Boutique River Cruises, which has 42 cabins swathed in marble and hand-carved wood, with beds dressed in fine Egyptian cotton sheets. The hotel scene is also, thankfully, getting a refresh with a new Mandarin Oriental slated for downtown Cairo in 2024; the forthcoming 200-room Four Seasons Hotel Luxor is scheduled to debut in 2025 — not that you should wait that long to see the ancient Valley of the Kings. — John Wogan');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('FW', 'For the Food - And Wine', 'Athens', 'https://www.travelandleisure.com/thmb/4Tm09YYxnWhGJXemX83SuI1IJpY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-four-seasons-astir-palace-athens-greece-WTG2023-c8e78b4925734089b2d2bafd7938eba4.jpg', 'It may have a reputation as a stopover city, but Athens deserves a closer look — and at least a few nights — in the year ahead. Not far from the Piraeus port, where travelers hop both domestic ferries and cruise ships that criss-cross the Mediterranean, the Athens Riviera has seen a surge of development. Four Seasons Astir Palace, which opened amid the pandemic, has a private beach on the sparkling Saronic Sea and two spaces designed by Swedish architect Martin Brudnizki, including a midcentury modern cocktail bar and Pelagos restaurant, which has already earned its first Michelin star. In the spring of 2023, One&Only Aesthesis will open just a few miles away, also along the waterfront. Next door is the brand-new Experience Park, with trails, fitness classes, fountains, a Zen garden, and bountiful native plants and flowers; it’s part of an $8-billion waterfront green space called The Ellinikon, on the former site of the city’s international airport, that’s still under development. In central Athens, the 2022 opening of the 43-room Xenodocheio Milos hotel in the Pláka neighborhood brings a bit of cosmopolitan verve, from the team behind international restaurant brand Estiatorio Milos. And while the Odeon of Herodes Atticus on the Acropolis isn’t new — the ancient amphitheater first opened about 1,900 years ago — it will bring back a full schedule of shows in 2023 after a pandemic-era slowdown. — Maya Kachroo-Levine');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
    ('FW', 'For the Food - And Wine', 'Central Florida', 'https://www.travelandleisure.com/thmb/-APGvCgk5zBtEczokOXYNa0XvW8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-central-florida-star-wars-galactic-starcruiser-WTG2023-e8679f8d556e43f79568c108e7870c06.jpg', 'This fall, Hurricane Ian took 81 lives and caused $60 billion in damage across Florida. While the hard-hit southwestern part of the state continues to recover, Visit Florida president and CEO Dana Young said in October that other regions are ready to welcome travelers back. Central Florida in particular is worth a closer look, thanks to its ever-growing hospitality scene. Orlando and Tampa recently won a combined 14 Michelin accolades in 2022, when the guidebook publisher released its first-ever guide to Florida restaurants. The area’s family-friendly draws are better than ever: Disney’s recently opened, highly immersive Star Wars: Galactic Starcruiser is a two-night adventure that takes themed entertainment to the next level by allowing guests to eat, sleep, and breathe Star Wars with lightsaber training, out-of-this-world dining (blue shrimp, anyone?), and a trip to Batuu at Disney’s Hollywood Studios. Meantime, Walt Disney World’s 50th anniversary celebrations continue through March 2023, with limited-time eats, nighttime spectaculars, and festive décor. In Tampa, the latest Edition Hotel just opened with a sprawling rooftop pool club and restaurant from chef John Fraser. And getting both to and around Central Florida is easier than ever, with the recent opening of Orlando International Airport’s new 15-gate Terminal C and Brightline rail service connecting Orlando to South Florida destinations including Miami and West Palm Beach beginning in 2023. — Elizabeth Rhodes');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('BT', 'For Big-city Thrills', 'Copenhagen', 'https://www.travelandleisure.com/thmb/2sXG2WFHCdUoIW2f8bPsfRmNoW0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-copenhagen-denmark-WTG2023-d22e6dcdeff7405f98d01e5f8a7a0712.jpg', 'The eternally cool city will highlight its prowess with all things design, as the official UNESCO World Capital of Architecture in 2023. Venues across Copenhagen — contemporary parks, starchitect-designed skyscrapers, even typically humdrum infrastructure like playgrounds — will host events and visitors for a look at the future of the urban environment. One highlight will be the Copenhill Power Plant, the cleanest waste-to-energy plant in the world — that’s also the site of an artificial ski slope. “We’re going to do a lot of open-house events where 50 different venues are going to be open to the public that are usually closed to visitors,” said Copenhagen’s city architect Camilla van Deurs, who mentioned as examples churches; bridges; and the Danmarks Nationalbank, the central bank building planned in part by Danish design legend Arne Jacobsen. “Superkilen,” van Deurs said, “is a playground for kids and adults — and a cultural hub in the middle of Nørrebro, the most ethnically mixed neighborhood in Copenhagen.” New places to stay in the city also deliver a signature blend of modernism and hygge: Find it at the single-suite Kaj Hotel, which floats on a canal near Copenhagen Opera House, or the colorful new 25 Hours Hotel Copenhagen. — Tim Latterner');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('BT', 'For Big-city Thrills', 'Houston', 'https://www.travelandleisure.com/thmb/Ktt7bVOI5x3XznOuZOhxK12ge2M=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-houston-texas-botanic-garden-WTG2023-33e89d765b4749848d641fc2afd03dfd.jpg', 'The 2020 opening of the Kinder Building, the latest addition to the Museum of Fine Arts Houston, cemented the city’s spot among true international arts destinations. The recent reopening of the Rothko Chapel, after a $35-million renovation, has only reinforced that reputation. Today, a wealth of new ventures is poised to raise the profile of Texas’s largest city in other categories as well. Opening next year, the JMK5 Arena will transform a disused racetrack into a 12,500-seat concert stadium poised to rival the venues of Vegas. It arrives on the heels of the relatively more intimate 713 Music Hall, which has attracted artists ranging from Judas Priest to Lil Nas X. The Houston Zoo is undergoing a much-delayed expansion that will include a Galápagos Islands–themed exhibit, which will feature an underwater tunnel and a penguin habitat. And the Houston Botanic Gardens, which opened in 2020, features 132 acres of diverse ecosystems, from wetlands to prairie. — Peter Terzian');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('MW', 'For Moments on the Water', 'Cape Verde, The Gambia, Ghana, and Guinea-Bissau', 'https://www.travelandleisure.com/thmb/Q0yAwLsgBffxIPLG2yZ2vuUYzzo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-santo-antao-cape-verde-islands-WTG2023-82a076b4cf2848dda0a553f5d8faaadf.jpg', 'Though Ghana has, in recent years, surged in popularity as a destination for American visitors, particularly Black Americans, West Africa remains unfamiliar to many. One solution may be the innovative West Africa Archipelago cruises that Hurtigruten Expeditions aims to launch in November 2023. These two-week trips, aboard the line’s 180-passenger Spitsbergen, will stop in ports in four countries, with a huge array of activities on the expedition schedule: visits to historically important sites including Gorée Island; wildlife-watching forays to spot hippos and manatees; and adventures such as scaling volcanoes and scrambling across lava fields. Though some cruise lines occasionally stop in West African ports, Hurtigruten’s deep focus on the region represents a step change — one that’s driven by passenger demand, said Asta Lassesen, the CEO of Hurtigruten Expeditions. “These islands are not as known as our other destinations, but they are teeming with unique wildlife, different cultures, and offer completely different experiences than you’d find in a traditional cruise destination,” Lassesen told T+L. — Paul Brady');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('MW', 'For Moments on the Water', 'Coastal Ecuador', 'https://www.travelandleisure.com/thmb/PzBHi31WukOnioNmabSWe9WbDvc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-coastal-ecuador-kontiki-WTG2023-31ac443642db4c3688a06f31abbd3c3a.jpg', 'Many travelers know the historic capital city of Quito and the incredibly biodiverse Galápagos Islands, but now''s the time to visit Ecuador’s stunning Pacific coastline. From surf towns like Montañita to the preserved beaches and cloud forest of Machalilla National Park, coastal Ecuador is packed with outdoor adventures and stunning scenery. Kontiki Expeditions unlocks the region with eight-day yacht cruises that visit five of the country’s 24 provinces, hitting destinations including Isla de la Plata and Salinas. A member of Small Luxury Hotels of the World, Kontiki Expeditions operates an intimate ship with just nine staterooms, refined outdoor and indoor spaces, and a nearly 1:1 crew-to-guest ratio. (Guests can book an individual room, or charter the entire 18-passenger yacht.) Getting there has gotten smoother, too: U.S. airlines including American, JetBlue, and Spirit now offer direct flights to Guayaquil, from which Kontiki Expeditions trips depart. — Elizabeth Rhodes');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('FN', 'For Fresh Air and Nature', 'Andorra', 'https://www.travelandleisure.com/thmb/vlfZkWAhSn70UypPjTERT2eJBDE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-andorra-vallnord-pal-arinsal-ski-WTG2023-2225c90b06e3441fb4c061a37ea9efcf.jpg', 'This tiny European country, which at 181 square miles is smaller than Chicago, could soon turn into one of the world’s biggest ski destinations. The mountainous country, situated between France and Spain, has long been known for its reliable December-to-April conditions thanks to its high-altitude perch in the Pyrenees. But now, for the first time, three Andorra ski areas have been added to the Ikon Pass, putting a collective 7,600 acres of downhill terrain across 215 runs and 123 lifts into play for holders of the global lift ticket. At the same time, the three destinations of Grandvalira, Ordino Arcalís, and Pal-Arinsal (or, collectively, the Grandvalira Resorts Andorra) will be available on a single local Andorra Pass, which starts at about $50 a day, a bargain by any big-mountain standards. Alternatively, visitors can opt for a newly launched Nord Pass, a multi-day ticket that works at both Ordino Arcalís and Pal-Arinsal for less than $40 per day. So, while these affordable mountains remain a bit of a challenge to reach — Grandvalira can be a four-hour drive from Barcelona — the days of smaller crowds may soon be a thing of the past. — Jamie Aranoff');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('FN', 'For Fresh Air and Nature', 'Asheville, North Carolina', 'https://www.travelandleisure.com/thmb/yKHbidU_dBdwiW8MFXEtsQmMsk4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-sw-market-asheville-north-carolina-WTG2023-ec0663307a644f7a86e9b6c72f8e1454.jpg', 'This flannel-clad city in the Blue Ridge Mountains checks all the boxes, with year-round outdoor activities, sophisticated dining, and easy access, whether you’re driving or flying. (Asheville Regional Airport is on pace for a record-breaking 2022, with service from 25 destinations.) But the year ahead offers more reasons to visit, starting with some cool new places to stay: Wrong Way River Lodge has a collection of A-frame cabins along the French Broad River that are perfect for white-water rafters. AutoCamp Asheville, another glamping-esque abode with Airstream campers, is slated to open by mid-2023. Downtown, the new Restoration Hotel promises a properly plush stay; its sister property in Charleston consistently ranks in T+L''s World''s Best Awards. (For those who’d rather be even closer to nature, The Glamping Collective is a newly opened, 160-acre site with domed pods and glass cabins situated a short drive from the city.) Asheville’s food scene has fresh energy from S&W Market, Asheville’s first food hall and the brainchild of award-winning chef Meherwan Irani. For all that’s new, visitors shouldn’t skip the old standbys: French Broad Chocolates is a local fave that’s since gone national, and Battery Park Book Exchange is the prime spot for a late-night glass of Champagne amid dusty bookshelves. — Samantha Falewée');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('BV', 'For Beach Vibes', 'Bermuda', 'https://www.travelandleisure.com/thmb/3lBAjRRVXxm1ohbzGnmv1oEl70w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-sunken-harbor-club-bermuda-WTG2023-deb03391dbc94a7dbca996d2af9bac0b.jpg', 'Already a favorite weekend getaway for East Coasters, Bermuda will become even easier to get to in 2023. American Airlines resumed flights to the island from New York City’s John F. Kennedy International in November, which the carrier had paused in the early days of the pandemic. Upon arrival at L.F. Wade International, travelers are now greeted in a new $400-million terminal with automated immigration gates and preclearance for U.S.-bound passengers — plus unexpected extras like a putting green and an outdoor nature trail. Bermuda’s resort stock is on the rise, too: Cambridge Beaches Resort & Spa recently debuted a top-to-bottom renovation, adding villas and a Bermudian outpost of Sunken Harbor Club, the tropical cocktail bar above Brooklyn, New York’s wildly popular steakhouse Gage & Tollner. The St. Regis Bermuda is another high-end hotel option, which opened in 2021 with the nation’s first casino and incredible views of Fort St. Catherine. The island recently rolled back all COVID-19 entry requirements, but the Atlantic country’s remote work program — which launched in July 2020 and allows for stays up to one year — is still running for anyone looking to make its pink-sand beaches a new home base. — Liz Cantrell');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('BV', 'For Beach Vibes', 'Cayman Islands', 'https://www.travelandleisure.com/thmb/JbXl8DRJMORejHbGV9gtKTIKklk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-cayman-islands-snorkeling-WTG2023-981b4d704d2c4c039731928f873b4e4b.jpg', 'It just keeps getting easier to visit the Caymans. As of fall 2022, Cayman Airways flies nonstop from Los Angeles International to Grand Cayman, the first direct route from the West Coast to the British territory. “Getting to Hawaii takes longer,” said Kenneth Bryan, Cayman Islands honorable minister for tourism and transport, in an interview with T+L. Wherever they’re flying in from, visitors will find plenty of new offerings along Seven Mile Beach, on Grand Cayman’s west shore. Chief among them is the freshly renovated Ritz-Carlton, Grand Cayman, which is now outfitted with a La Prairie Spa and Saint June restaurant, complete with a beachfront bar. (The property is thankfully still home to the long-running, annual Cayman Cookout.) For travelers who prefer heart-pumping adventure to pool- or beachside relaxation, the Caymans can deliver: Hiking reserves like the 100-year-old Mastic Trail on Grand Cayman or the Bluff on Cayman Brac may not be as well known as the islands’ beaches — but they should be. Meanwhile a growing art scene is beginning to draw international attention, thanks to shows at the well-established National Gallery of the Cayman Islands as well as the vibey, creative atmosphere at new hotels such as Palm Heights, as T+L recently reported. — Christine Burroni');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('TF', 'For a Look at the Future', 'Bhutan', 'https://www.travelandleisure.com/thmb/L0heT-ahRVSr53dh5lxb7nEG6qA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-trans-bhutan-trail-WTG2023-c2f73386fe1f4363917f1b7c22a51d89.jpg', 'This past September, Bhutan, the impossibly scenic country between India and China, reopened to tourists after 30 months. But that’s nothing compared to the 60 years it’s taken to redevelop the 250-mile Trans-Bhutan Trail, which also reopened that month. Once the only way to travel across the Himalayan kingdom, the ancient pilgrimage route is now one of Bhutan’s biggest draws, a must-see for hikers, bikers, and other outdoorsy types. The trail connects 400 historic sites, with museums, fortresses, and temples along the way — plus stunning natural scenery and seemingly endless views. As part of its reopening, Bhutan has ended its policy requiring visitors to be accompanied 24/7 by a guide; instead, the nation has implemented an increased tourism tax, or Sustainable Development Fee, which is intended to fund social and cultural programs, infrastructure improvements, and environmental conservation. (The $200-a-day charge, up from $65, is also deliberately expensive, in an effort to keep visitor numbers low.) On the hotel front, Six Senses opened its fifth and final Bhutan lodge, Six Senses Bumthang, in March 2020, but the eco hideaway tucked in a pine forest in the town of Jakar, of course, has only just become accessible to foreigners. — Alisha Prakash');

INSERT INTO main_app_place(type, typefull, name, image, bio)
    VALUES
        ('TF', 'For a look at the Future', 'Boten-Vientiane Railway, Laos', 'https://www.travelandleisure.com/thmb/CHW90Yq3CP7R9kX5Ejjitk_s4fY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-buten-vientiane-railway-laos-WTG2023-485151f730aa417bb1f9838244af5c3e.jpg', 'It’s not every day the world gets a new cross-country railroad. The ambitious Boten–Vientiane railway that stretches across Laos may have opened for business in late 2021, but now’s the time to jump aboard, as travel to Asia reopens to American visitors. The remarkable engineering project is one of many financed by China as part of the country’s Belt and Road Initiative that builds heavy infrastructure across Africa and Asia. In this case, the train has dramatically slashed travel times across the difficult-to-drive if strikingly beautiful landscapes of Laos: Trips that would’ve taken a full day by road can now be done in just a couple hours of train-carriage comfort, as T+L recently reported. The route runs from the northern border town of Boten to Luang Prabang, which is known for its many temples. It then continues on to Vang Vieng, a gateway to some of the country’s most dramatic landscapes, before arriving in the capital, Vientiane, on the border with Thailand. Intermediate stations will help open up to visitors parts of the country that haven’t historically benefited from tourism, as Ruben Derksen, director of product and digital at Bangkok-based tour operator Exo Travel, told T+L. In the years ahead, the 257-mile railway may become even more critical, as just one segment of a Singapore to Shanghai route that will make continent-spanning journeys not just possible, but pleasant. — Paul Brady');