 INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For Cultural Riches', 'Alexandria, Virginia', 'https://www.travelandleisure.com/thmb/MfbcFrbzf8_tHsBtuYaKl4jHJ7s=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-king-street-alexandria-virginia-WTG2023-904fefe1290f4a3a91b53a7b40f61ae9.jpg', 'With postcard-perfect cobblestone streets and quick access to the wineries of northern Virginia, Alexandria is an easy city to love. But these days, the reason to go is to see how effectively the city is confronting its own history, as destinations across the American South grapple with the legacy of the Confederacy. Alexandria, which was founded as a tobacco port in 1749, was for decades of the 19th century the site of the country’s largest domestic slave trade. Today, the Freedom House Museum has three new exhibitions honoring the people who were forcibly brought here. Meanwhile, the African American Heritage Trail, which opened in 2020, follows the Potomac River and encompasses nearly 200 years of history at 11 stops, such as the Torpedo Factory, where many Black men and women worked during World War II. An extension of the route will debut in February 2023 with 20 new stops, including Waterfront Park, the port from which enslaved people were trafficked to places like New Orleans. At Jones Point Park, visitors can learn about Benjamin Banneker, an inventor, mathematician, and free African American from Maryland who was instrumental in the 1791 surveying team that determined the border of the new U.S. capital of Washington, D.C. (For an even deeper look at the city’s Black experience, book with Manumission Tours, which is run by a fourth-generation Alexandrian.) The city’s most elegant stay is Morrison House Old Town Alexandria, Autograph Collection, which was recently voted one of the best city hotels in the continental U.S. in T+L’s 2022 World’s Best Awards. A new Hotel AKA is slated to open in Old Town in winter 2023. — Liz Cantrell');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For the Food - And Wine', 'Athens', 'https://www.travelandleisure.com/thmb/4Tm09YYxnWhGJXemX83SuI1IJpY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-four-seasons-astir-palace-athens-greece-WTG2023-c8e78b4925734089b2d2bafd7938eba4.jpg', 'It may have a reputation as a stopover city, but Athens deserves a closer look — and at least a few nights — in the year ahead. Not far from the Piraeus port, where travelers hop both domestic ferries and cruise ships that criss-cross the Mediterranean, the Athens Riviera has seen a surge of development. Four Seasons Astir Palace, which opened amid the pandemic, has a private beach on the sparkling Saronic Sea and two spaces designed by Swedish architect Martin Brudnizki, including a midcentury modern cocktail bar and Pelagos restaurant, which has already earned its first Michelin star. In the spring of 2023, One&Only Aesthesis will open just a few miles away, also along the waterfront. Next door is the brand-new Experience Park, with trails, fitness classes, fountains, a Zen garden, and bountiful native plants and flowers; it’s part of an $8-billion waterfront green space called The Ellinikon, on the former site of the city’s international airport, that’s still under development. In central Athens, the 2022 opening of the 43-room Xenodocheio Milos hotel in the Pláka neighborhood brings a bit of cosmopolitan verve, from the team behind international restaurant brand Estiatorio Milos. And while the Odeon of Herodes Atticus on the Acropolis isn’t new — the ancient amphitheater first opened about 1,900 years ago — it will bring back a full schedule of shows in 2023 after a pandemic-era slowdown. — Maya Kachroo-Levine');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For Big-city Thrills', 'Copenhagen', 'https://www.travelandleisure.com/thmb/2sXG2WFHCdUoIW2f8bPsfRmNoW0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-copenhagen-denmark-WTG2023-d22e6dcdeff7405f98d01e5f8a7a0712.jpg', 'The eternally cool city will highlight its prowess with all things design, as the official UNESCO World Capital of Architecture in 2023. Venues across Copenhagen — contemporary parks, starchitect-designed skyscrapers, even typically humdrum infrastructure like playgrounds — will host events and visitors for a look at the future of the urban environment. One highlight will be the Copenhill Power Plant, the cleanest waste-to-energy plant in the world — that’s also the site of an artificial ski slope. “We’re going to do a lot of open-house events where 50 different venues are going to be open to the public that are usually closed to visitors,” said Copenhagen’s city architect Camilla van Deurs, who mentioned as examples churches; bridges; and the Danmarks Nationalbank, the central bank building planned in part by Danish design legend Arne Jacobsen. “Superkilen,” van Deurs said, “is a playground for kids and adults — and a cultural hub in the middle of Nørrebro, the most ethnically mixed neighborhood in Copenhagen.” New places to stay in the city also deliver a signature blend of modernism and hygge: Find it at the single-suite Kaj Hotel, which floats on a canal near Copenhagen Opera House, or the colorful new 25 Hours Hotel Copenhagen. — Tim Latterner');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For Moments on the Water', 'Cape Verde, The Gambia, Ghana, and Guinea-Bissau', 'https://www.travelandleisure.com/thmb/Q0yAwLsgBffxIPLG2yZ2vuUYzzo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-santo-antao-cape-verde-islands-WTG2023-82a076b4cf2848dda0a553f5d8faaadf.jpg', 'Though Ghana has, in recent years, surged in popularity as a destination for American visitors, particularly Black Americans, West Africa remains unfamiliar to many. One solution may be the innovative West Africa Archipelago cruises that Hurtigruten Expeditions aims to launch in November 2023. These two-week trips, aboard the line’s 180-passenger Spitsbergen, will stop in ports in four countries, with a huge array of activities on the expedition schedule: visits to historically important sites including Gorée Island; wildlife-watching forays to spot hippos and manatees; and adventures such as scaling volcanoes and scrambling across lava fields. Though some cruise lines occasionally stop in West African ports, Hurtigruten’s deep focus on the region represents a step change — one that’s driven by passenger demand, said Asta Lassesen, the CEO of Hurtigruten Expeditions. “These islands are not as known as our other destinations, but they are teeming with unique wildlife, different cultures, and offer completely different experiences than you’d find in a traditional cruise destination,” Lassesen told T+L. — Paul Brady');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For Fresh Air and Nature', 'Andorra', 'https://www.travelandleisure.com/thmb/vlfZkWAhSn70UypPjTERT2eJBDE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-andorra-vallnord-pal-arinsal-ski-WTG2023-2225c90b06e3441fb4c061a37ea9efcf.jpg', 'This tiny European country, which at 181 square miles is smaller than Chicago, could soon turn into one of the world’s biggest ski destinations. The mountainous country, situated between France and Spain, has long been known for its reliable December-to-April conditions thanks to its high-altitude perch in the Pyrenees. But now, for the first time, three Andorra ski areas have been added to the Ikon Pass, putting a collective 7,600 acres of downhill terrain across 215 runs and 123 lifts into play for holders of the global lift ticket. At the same time, the three destinations of Grandvalira, Ordino Arcalís, and Pal-Arinsal (or, collectively, the Grandvalira Resorts Andorra) will be available on a single local Andorra Pass, which starts at about $50 a day, a bargain by any big-mountain standards. Alternatively, visitors can opt for a newly launched Nord Pass, a multi-day ticket that works at both Ordino Arcalís and Pal-Arinsal for less than $40 per day. So, while these affordable mountains remain a bit of a challenge to reach — Grandvalira can be a four-hour drive from Barcelona — the days of smaller crowds may soon be a thing of the past. — Jamie Aranoff');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For Beach Vibes', 'Bermuda', 'https://www.travelandleisure.com/thmb/3lBAjRRVXxm1ohbzGnmv1oEl70w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-sunken-harbor-club-bermuda-WTG2023-deb03391dbc94a7dbca996d2af9bac0b.jpg', 'Already a favorite weekend getaway for East Coasters, Bermuda will become even easier to get to in 2023. American Airlines resumed flights to the island from New York City’s John F. Kennedy International in November, which the carrier had paused in the early days of the pandemic. Upon arrival at L.F. Wade International, travelers are now greeted in a new $400-million terminal with automated immigration gates and preclearance for U.S.-bound passengers — plus unexpected extras like a putting green and an outdoor nature trail. Bermuda’s resort stock is on the rise, too: Cambridge Beaches Resort & Spa recently debuted a top-to-bottom renovation, adding villas and a Bermudian outpost of Sunken Harbor Club, the tropical cocktail bar above Brooklyn, New York’s wildly popular steakhouse Gage & Tollner. The St. Regis Bermuda is another high-end hotel option, which opened in 2021 with the nation’s first casino and incredible views of Fort St. Catherine. The island recently rolled back all COVID-19 entry requirements, but the Atlantic country’s remote work program — which launched in July 2020 and allows for stays up to one year — is still running for anyone looking to make its pink-sand beaches a new home base. — Liz Cantrell');

    INSERT INTO main_app_place(TYPE_OF_PLACE_CHOICES, name, image, bio)
    VALUES
        ('For a Look at the Future', 'Bhutan', 'https://www.travelandleisure.com/thmb/L0heT-ahRVSr53dh5lxb7nEG6qA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/TAL-trans-bhutan-trail-WTG2023-c2f73386fe1f4363917f1b7c22a51d89.jpg', 'This past September, Bhutan, the impossibly scenic country between India and China, reopened to tourists after 30 months. But that’s nothing compared to the 60 years it’s taken to redevelop the 250-mile Trans-Bhutan Trail, which also reopened that month. Once the only way to travel across the Himalayan kingdom, the ancient pilgrimage route is now one of Bhutan’s biggest draws, a must-see for hikers, bikers, and other outdoorsy types. The trail connects 400 historic sites, with museums, fortresses, and temples along the way — plus stunning natural scenery and seemingly endless views. As part of its reopening, Bhutan has ended its policy requiring visitors to be accompanied 24/7 by a guide; instead, the nation has implemented an increased tourism tax, or Sustainable Development Fee, which is intended to fund social and cultural programs, infrastructure improvements, and environmental conservation. (The $200-a-day charge, up from $65, is also deliberately expensive, in an effort to keep visitor numbers low.) On the hotel front, Six Senses opened its fifth and final Bhutan lodge, Six Senses Bumthang, in March 2020, but the eco hideaway tucked in a pine forest in the town of Jakar, of course, has only just become accessible to foreigners. — Alisha Prakash');